<?php
return [
    'settings' => [
        'hero_eyebrow' => 'Federal Republic of Nigeria',
        'hero_headline' => 'Defending the sovereignty of Nigeria.',
        'hero_body' => 'The Federal Ministry of Defence — the apex policy authority overseeing the Nigerian Armed Forces — provides strategic leadership for a modern, professional, mission-ready military in the service of more than 220 million citizens of the Federal Republic.',
        'last_reviewed' => 'June 2026',
        'ministry_name' => 'Federal Ministry of Defence',
        'country' => 'Federal Republic of Nigeria',
    ],
    'slides' => [
        [
            'img' => 'assets/images/hero/slide-8.jpg',
            'alt' => 'Nigerian Army soldiers on patrol vehicle in counter-terrorism operations',
            'role' => 'Nigerian Army',
            'name' => 'Counter-terrorism operations — Nigerian soldiers engaged in active theatre operations.',
        ],
        [
            'img' => 'assets/images/hero/slide-2.jpg',
            'alt' => 'Nigerian Navy special boat service operators on patrol in the Gulf of Guinea',
            'role' => 'Nigerian Navy',
            'name' => 'Maritime special forces securing Nigeria\'s territorial waters and the Gulf of Guinea.',
        ],
        [
            'img' => 'assets/images/hero/slide-3.jpg',
            'alt' => 'Nigerian Air Force Mi-35 attack helicopter NAF 530 in flight',
            'role' => 'Nigerian Air Force',
            'name' => 'NAF 530 on deployment — projecting air power in defence of Nigeria\'s sovereign skies.',
        ],
        [
            'img' => 'assets/images/hero/slide-4.jpg',
            'alt' => 'Nigerian Army honour guard inspection in full ceremonial uniform',
            'role' => 'Nigerian Army',
            'name' => 'Precision and ceremony — the Nigerian Army honour guard stands ready in service of the nation.',
        ],
        [
            'img' => 'assets/images/hero/slide-5.jpg',
            'alt' => 'Nigerian Air Force fighter jets taxiing in formation on the runway',
            'role' => 'Nigerian Air Force',
            'name' => 'Strike aircraft lined up and ready — the Nigerian Air Force maintains constant operational readiness.',
        ],
        [
            'img' => 'assets/images/hero/slide-6.jpg',
            'alt' => 'Nigerian Air Force fighter jets lined up on the flight line with cockpits open',
            'role' => 'Nigerian Air Force',
            'name' => 'Fighter jets on the tarmac — air power standing by in the service of Nigeria\'s national security.',
        ],
        [
            'img' => 'assets/images/hero/slide-7.jpg',
            'alt' => 'Nigerian Air Force fighter jet in flight above clouds, fully armed',
            'role' => 'Nigerian Air Force',
            'name' => 'Armed and airborne — Nigeria\'s air combat capability ready to defend sovereign skies.',
        ],
        [
            'img' => 'assets/images/hero/slide-1.jpg',
            'alt' => 'Ship House — Federal Ministry of Defence headquarters, Abuja',
            'role' => 'Ship House, Abuja',
            'name' => 'Seat of Nigeria\'s defence policy — home of the Federal Ministry of Defence.',
        ],
    ],
    'leadership' => [
        'minister' => [
            'title' => 'Honourable Minister of Defence',
            'name' => 'General Christopher Gwabin Musa (rtd)',
            'bio' => 'Leads the strategic modernisation of Nigeria\'s defence architecture — anchored on the welfare of officers and ratings, indigenous defence-industrial capacity, and citizen-centred accountability.',
            'photo_url' => 'assets/images/headshots/general-christopher-musa.jpeg',
            'profile_link' => 'minister.html',
        ],
        'ministerOfState' => [
            'title' => 'Honourable Minister of State',
            'name' => 'Dr. Bello M. Matawalle, MON',
            'bio' => 'Supports the Honourable Minister on strategic, security-sector and welfare portfolios, with focus on community peace-building and counter-extremism programmes.',
            'photo_url' => 'assets/images/headshots/dr-bello-matawalle.jpg',
            'profile_link' => 'minister-of-state.html',
        ],
        'permSec' => [
            'title' => 'Permanent Secretary',
            'name' => 'Permanent Secretary',
            'bio' => 'Accounting and chief administrative officer; coordinates the departments, units and tri-service interface of the Ministry.',
            'photo_url' => 'assets/images/headshots/permanent-secretary.jpeg',
            'profile_link' => 'management.html',
        ],
    ],
    'press' => [
        [
            'slug' => 'defence-minister-pledges-amce',
            'date' => '11 May 2026',
            'category' => 'Press Office',
            'title' => 'Defence Minister pledges to boost military healthcare, reduce medical tourism during AMCE visit',
            'excerpt' => 'The Honourable Minister has pledged the Ministry\'s commitment to strengthening military healthcare and reducing medical tourism, during a working visit to the African Medical Centre of Excellence in Abuja.',
            'img' => 'https://defence.gov.ng/wp-content/uploads/slider/cache/5c91a2fb5a3c3d7d91aa26fb98ea005d/WhatsApp-Image-2026-05-08-at-09.51.56.jpg',
            'url' => 'https://defence.gov.ng/2026/05/11/defence-minister-pledges-to-boost-military-healthcare-reduce-medical-tourism-during-amce-visit/',
        ],
        [
            'slug' => 'icrc-humanitarian',
            'date' => '08 May 2026',
            'category' => 'Press Office',
            'title' => 'Defence Minister commends ICRC for humanitarian services in the country',
            'excerpt' => 'The Honourable Minister of Defence commended the International Committee of the Red Cross for its humanitarian engagement across conflict-affected communities.',
            'img' => 'https://defence.gov.ng/wp-content/uploads/slider/cache/7ed124706b9db62fa4aae0e8bdc44f70/WhatsApp-Image-2026-05-06-at-09.44.49.jpg',
            'url' => 'https://defence.gov.ng/2026/05/08/defence-minister-commends-icrc-for-humanitarian-services-in-the-country/',
        ],
        [
            'slug' => 'regional-security-meeting',
            'date' => '06 May 2026',
            'category' => 'Press Office',
            'title' => 'Defence Minister participates in regional security meeting',
            'excerpt' => 'The Honourable Minister reaffirmed Nigeria\'s commitment to regional cooperation and collective security during a high-level consultation with West African counterparts.',
            'img' => 'https://defence.gov.ng/wp-content/uploads/slider/cache/f2ac3e9cb69b47524dec83e6268b40b1/WhatsApp-Image-2026-05-05-at-16.06.33.jpg',
            'url' => 'https://defence.gov.ng/2026/05/06/defence-minister-participates-in-regional-security-meeting/',
        ],
        [
            'slug' => 'prestigious-fellowship',
            'date' => '06 May 2026',
            'category' => 'Press Office',
            'title' => 'Defence Minister conferred with prestigious fellowship',
            'excerpt' => 'The Honourable Minister was honoured with an honorary fellowship in recognition of his contributions to national security and defence reform.',
            'img' => 'https://defence.gov.ng/wp-content/uploads/slider/cache/b64dada37ea1a198b4a6e0382f45f0c0/WhatsApp-Image-2026-05-05-at-04.41.488-1.jpg',
            'url' => 'https://defence.gov.ng/2026/05/06/defence-minister-conferred-with-prestigious-fellowship/',
        ],
        [
            'slug' => 'musa-students-security',
            'date' => '05 May 2026',
            'category' => 'Press Office',
            'title' => 'Gen. Musa urges Nigerian students to play active role in national security',
            'excerpt' => 'Gen. Musa urged students and youth to take ownership of national security through civic responsibility and lawful conduct.',
            'img' => 'https://defence.gov.ng/wp-content/uploads/slider/cache/7d5dab6eb3370ef45d22dfbeceb170b0/WhatsApp-Image-2026-05-05-at-04.41.4644.jpg',
            'url' => 'https://defence.gov.ng/2026/05/05/gen-musa-urges-nigerian-students-to-play-active-role-in-national-security/',
        ],
        [
            'slug' => 'veritas-university',
            'date' => '05 May 2026',
            'category' => 'Press Office',
            'title' => 'Hon. Minister receives Veritas University Political Science delegation',
            'excerpt' => 'The Honourable Minister received a delegation from the Department of Political Science and Diplomacy of Veritas University at Ship House, Abuja.',
            'img' => 'https://defence.gov.ng/wp-content/uploads/slider/cache/f2ac3e9cb69b47524dec83e6268b40b1/WhatsApp-Image-2026-05-05-at-16.06.33.jpg',
            'url' => 'https://defence.gov.ng/2026/05/05/the-honourable-minister-of-defence-general-christopher-gwabin-musa-ofrrtd-received-a-delegation-from-the-department-of-political-science-and-diplomacy-veritas-university/',
        ],
        [
            'slug' => 'three-committees-inaugurated',
            'date' => '30 April 2026',
            'category' => 'Press Office',
            'title' => 'Hon. Minister inaugurates three committees at Ship House',
            'excerpt' => 'The Honourable Minister inaugurated three strategic committees at Ship House, Abuja, in furtherance of the Ministry\'s reform agenda.',
            'img' => 'https://defence.gov.ng/wp-content/uploads/slider/cache/de24e192a317d951778e07962e82686d/WhatsApp-Image-2026-04-29-at-21.34.414.jpg',
            'url' => 'https://defence.gov.ng/2026/04/30/the-honourable-minister-of-defence-general-christopher-gwabin-musa-rtd-inaugurated-three-committees-at-the-ministerys-conference-room-ship-house-abuja-on-wednesday-29-april-2026/',
        ],
        [
            'slug' => 'strategic-committees-security-veterans',
            'date' => '30 April 2026',
            'category' => 'Press Office',
            'title' => 'Defence Ministry inaugurates strategic committees to strengthen national security and veterans welfare',
            'excerpt' => 'The Ministry inaugurated strategic committees aimed at strengthening national security architecture and veterans welfare.',
            'img' => 'https://defence.gov.ng/wp-content/uploads/slider/cache/39e7bd9f42f86e2e15e02a7a8e72b6bb/WhatsApp-Image-2026-04-29-at-21.34.426.jpg',
            'url' => 'https://defence.gov.ng/2026/04/30/defence-ministry-inaugurates-strategic-committees-to-strengthen-national-security-and-veterans-welfare/',
        ],
    ],
];
